ami_win = "ami-041114ddee4a98333"
octo_url = "https://download.octopusdeploy.com/octopus/Octopus.Tentacle.3.24.0-x64.msi"
octo_server = "#{octo_server}"
octo_api = "#{octo_api}"
octoenv = "#{octoenv}"
octorole = "#{octorole}"
output = "C:\install" 